const express = require('express')
const router = express.Router()
const videoController = require('../controller/videoController')
const vodController = require('../controller/vodController')
const { verfiyToken } = require('../util/jwt')
const validator = require('../middleware/validator/videoValidator')
router
    .get('/list',videoController.list,vodController.getvodUrl)
    .get('/getvod',vodController.getvod)
    .post('/createVideo',verfiyToken(),validator.video,videoController.createVideo)
    .get('/video/:videoId',verfiyToken(),videoController.video)
    .post('/videoComment/:videoId',verfiyToken(),videoController.comment)
    .get('/videoCommentList/:videoId',videoController.commentList)
    .delete('/deleteComment/:videoId/:commentId',verfiyToken(),videoController.deleteComment)
    .get('/like/:videoId',verfiyToken(),videoController.like)
    .get('/likeList/:videoId',verfiyToken(),videoController.likeList)
    .get('/collect/:videoId',verfiyToken(),videoController.collect)
    .get('/gethots/:count',videoController.gethots)
module.exports = router